export { default as HistoryPage } from './HistoryPage/HistoryPage'
export { default as Admin } from './Admin/Admin'
export { default as AdminScrutinyEventsPage } from './AdminScrutinyEventsPage/AdminScrutinyEventsPage'
export { default as HomePage } from './HomePage/HomePage'
export { default as LoginPage } from './LoginPage/LoginPage'