using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using CalendarDay.Infrastructure.Persistence;

#nullable disable

namespace CalendarDay.Infrastructure.Migrations;

/// <summary>
/// display_order columns, the audiences table and the audit_logs table were documented in
/// Sql/20260508_add_*_order.sql and Sql/20260508_add_audit_log*.sql but never shipped as EF
/// migrations; production DBs created via MigrateAsync were missing them even though the model
/// snapshot already tracks them.
/// </summary>
[DbContext(typeof(CalendarDayDbContext))]
[Migration("20260520000000_AddDisplayOrderAndAuditLogs")]
public partial class AddDisplayOrderAndAuditLogs : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            ALTER TABLE "ResponsibleOptions"
                ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 0;

            WITH ordered AS (
                SELECT "Id", row_number() OVER (ORDER BY "Label", "Id") AS rn
                FROM "ResponsibleOptions"
            )
            UPDATE "ResponsibleOptions" r
            SET display_order = ordered.rn
            FROM ordered
            WHERE r."Id" = ordered."Id";
            """);

        migrationBuilder.Sql(
            """
            ALTER TABLE election_types
                ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 0;

            WITH ordered AS (
                SELECT id, row_number() OVER (ORDER BY id) AS rn
                FROM election_types
            )
            UPDATE election_types et
            SET display_order = ordered.rn
            FROM ordered
            WHERE et.id = ordered.id;
            """);

        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS audiences (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key varchar(200) NOT NULL,
                name varchar(500) NOT NULL,
                display_order integer NOT NULL DEFAULT 0,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT ix_audiences_key UNIQUE (key)
            );
            """);

        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS audit_logs (
                id uuid PRIMARY KEY,
                username varchar(320) NULL,
                action varchar(120) NOT NULL,
                details varchar(4000) NULL,
                endpoint varchar(1000) NOT NULL,
                method varchar(16) NOT NULL,
                status_code integer NOT NULL,
                ip_address varchar(64) NULL,
                created_at_utc timestamp with time zone NOT NULL DEFAULT now()
            );

            CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at_utc ON audit_logs (created_at_utc);
            CREATE INDEX IF NOT EXISTS ix_audit_logs_username ON audit_logs (username);
            CREATE INDEX IF NOT EXISTS ix_audit_logs_status_code ON audit_logs (status_code);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS audit_logs;");
        migrationBuilder.Sql("DROP TABLE IF EXISTS audiences;");
        migrationBuilder.Sql("ALTER TABLE election_types DROP COLUMN IF EXISTS display_order;");
        migrationBuilder.Sql("ALTER TABLE \"ResponsibleOptions\" DROP COLUMN IF EXISTS display_order;");
    }
}
